import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useMemo, useState } from 'react'
import { addDays, addMonths, addWeeks, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, parseISO, startOfMonth, startOfWeek, subDays, subMonths, subWeeks } from 'date-fns'
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Menu, Plus, Search, Settings2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { MeetingDialog } from '@/components/calendar/MeetingDialog'
import { blankMeeting, formatTime, Meeting, MeetingType, profile, sampleMeetings, UserProfile } from '@/lib/calendar'
import mark from '@/assets/buildicy-mark.png.asset.json'

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'Buildicy Calendar | Meetings, made clear' },
    { name: 'description', content: 'A focused calendar for Buildicy founders to organize meetings and reminders.' },
    { property: 'og:title', content: 'Buildicy Calendar | Meetings, made clear' },
    { property: 'og:description', content: 'A focused calendar for Buildicy founders to organize meetings and reminders.' },
    { property: 'og:type', content: 'website' },
    { name: 'twitter:card', content: 'summary_large_image' },
  ] }),
  component: CalendarApp,
})

type View = 'Month' | 'Week' | 'Day'
type Section = 'Calendar' | 'Upcoming' | 'Settings'
const views: View[] = ['Month', 'Week', 'Day']
const eventColors: Record<MeetingType, string> = { 'Client Meeting': 'bg-client', 'Internal Meeting': 'bg-internal', 'Follow-up': 'bg-followup', Important: 'bg-important', Other: 'bg-other' }
const eventBorders: Record<MeetingType, string> = { 'Client Meeting': 'border-client', 'Internal Meeting': 'border-internal', 'Follow-up': 'border-followup', Important: 'border-important', Other: 'border-other' }
const today = new Date()
const storageKey = 'buildicy-calendar-meetings-v1'

function UserProfileBlock({ user }: { user: UserProfile }) {
  return <div className="flex items-center gap-3 border-t border-border px-6 py-5"><div className="flex size-9 shrink-0 items-center justify-center rounded-sm bg-brand-soft font-display text-sm font-bold text-primary">{user.name[0]}</div><div className="min-w-0"><div className="truncate text-sm font-bold">{user.name}</div><div className="text-xs text-muted-foreground">{user.role}</div></div><span className="ml-auto size-2 rounded-full bg-internal" /></div>
}

function CalendarApp() {
  const [cursor, setCursor] = useState(today)
  const [selectedDate, setSelectedDate] = useState(today)
  const [view, setView] = useState<View>('Month')
  const [section, setSection] = useState<Section>('Calendar')
  const [meetings, setMeetings] = useState<Meeting[]>(() => sampleMeetings(today))
  const [loaded, setLoaded] = useState(false)
  const [active, setActive] = useState<Meeting | null>(null)
  const [dialogMode, setDialogMode] = useState<'create' | 'view' | 'edit'>('create')
  const [search, setSearch] = useState('')
  const [searchOpen, setSearchOpen] = useState(false)
  const [mobileMenu, setMobileMenu] = useState(false)
  useEffect(() => {
    try { const saved = localStorage.getItem(storageKey); if (saved) { const data = JSON.parse(saved); if (Array.isArray(data)) setMeetings(data) } } catch { /* Fall back to sample data. */ }
    setLoaded(true)
  }, [])
  useEffect(() => { if (loaded) localStorage.setItem(storageKey, JSON.stringify(meetings)) }, [meetings, loaded])
  const filtered = useMemo(() => meetings.filter(m => `${m.title} ${m.client} ${m.type}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => `${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`)), [meetings, search])
  const upcoming = filtered.filter(m => `${m.date}T${m.endTime}` >= format(today, "yyyy-MM-dd'T'HH:mm"))
  const todaysCount = meetings.filter(m => m.date === format(today, 'yyyy-MM-dd')).length
  const weekStart = startOfWeek(today, { weekStartsOn: 1 })
  const weekEnd = endOfWeek(today, { weekStartsOn: 1 })
  const weekCount = meetings.filter(m => { const d = parseISO(m.date); return d >= weekStart && d <= weekEnd }).length
  const periodLabel = view === 'Month' ? format(cursor, 'MMMM yyyy') : view === 'Week' ? `${format(startOfWeek(cursor, { weekStartsOn: 1 }), 'MMM d')} — ${format(endOfWeek(cursor, { weekStartsOn: 1 }), 'MMM d, yyyy')}` : format(cursor, 'MMMM d, yyyy')
  const move = (direction: number) => setCursor(current => view === 'Month' ? direction > 0 ? addMonths(current, 1) : subMonths(current, 1) : view === 'Week' ? direction > 0 ? addWeeks(current, 1) : subWeeks(current, 1) : addDays(current, direction))
  const create = (day = selectedDate) => { setActive(blankMeeting(day)); setDialogMode('create'); setMobileMenu(false) }
  const open = (meeting: Meeting) => { setActive(meeting); setDialogMode('view') }
  const save = (meeting: Meeting) => { const final = { ...meeting, id: meeting.id || crypto.randomUUID() }; setMeetings(current => meeting.id ? current.map(m => m.id === meeting.id ? final : m) : [...current, final]); setSelectedDate(parseISO(final.date)); setCursor(parseISO(final.date)); setActive(null) }
  const duplicate = (meeting: Meeting) => { const copy = { ...meeting, id: crypto.randomUUID(), title: `${meeting.title} (copy)` }; setMeetings(current => [...current, copy]); setActive(copy); setDialogMode('view') }
  const remove = (id: string) => { setMeetings(current => current.filter(m => m.id !== id)); setActive(null) }
  const selectSection = (next: Section) => { setSection(next); setMobileMenu(false) }
  return <div className="min-h-screen bg-background text-foreground lg:flex">
    {mobileMenu && <div className="fixed inset-0 z-30 bg-foreground/30 lg:hidden" onClick={() => setMobileMenu(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[246px] flex-col border-r border-border bg-card transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${mobileMenu ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex h-25 items-center justify-between border-b border-border px-5"><div className="flex items-center gap-2.5"><img src={mark.url} alt="Buildicy logo" className="size-11 object-contain" /><div className="font-display text-[15px] font-bold leading-[1.05]">BUILDICY<span className="block font-medium text-primary">CALENDAR<span className="text-foreground">.</span></span></div></div><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Close menu" onClick={() => setMobileMenu(false)}><X /></Button></div>
      <div className="px-4 pt-8"><div className="px-3 text-[10px] font-bold uppercase text-muted-foreground">Workspace / 01</div><nav className="mt-4 space-y-1">{([['Calendar', CalendarDays], ['Upcoming', Clock3], ['Settings', Settings2]] as const).map(([name, Icon]) => <Button key={name} variant="ghost" onClick={() => selectSection(name)} className={`h-11 w-full justify-start gap-3 rounded-sm px-3 text-sm font-semibold ${section === name ? 'bg-brand-soft text-primary hover:bg-brand-soft' : 'text-muted-foreground'}`}><Icon className="size-4" />{name}{section === name && <span className="ml-auto size-1.5 rounded-full bg-primary" />}</Button>)}</nav><Button onClick={() => create()} className="mt-9 h-11 w-full justify-between rounded-sm font-bold shadow-none"><span>New meeting</span><Plus className="size-4" /></Button></div>
      <div className="mt-auto"><div className="mx-6 mb-6 border-l-2 border-primary pl-3"><p className="text-[10px] font-bold uppercase text-muted-foreground">Make space for</p><p className="mt-1 font-display text-sm font-bold">the next big thing.</p></div><UserProfileBlock user={profile} /></div>
    </aside>
    <div className="min-w-0 flex-1">
      <header className="flex h-16 items-center justify-between gap-3 border-b border-border bg-card px-4 sm:px-8 lg:h-20 lg:px-10"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open menu" onClick={() => setMobileMenu(true)}><Menu /></Button><div><p className="hidden text-[10px] font-bold uppercase text-muted-foreground sm:block">Private workspace <span className="mx-2 text-border">/</span> {section}</p><p className="font-display text-sm font-bold sm:text-base">BUILDICY <span className="text-primary">CALENDAR</span></p></div></div><div className="flex items-center gap-2 sm:gap-3"><div className={`flex items-center overflow-hidden border border-border bg-background transition-all ${searchOpen ? 'w-42 sm:w-64' : 'w-9 border-transparent sm:w-52 sm:border-border'}`}><Button variant="ghost" size="icon" className="shrink-0" aria-label="Search meetings" onClick={() => setSearchOpen(true)}><Search className="size-4" /></Button><input aria-label="Search meetings" placeholder="Search meetings..." className={`min-w-0 flex-1 bg-transparent pr-2 text-xs outline-none ${searchOpen ? 'block' : 'hidden sm:block'}`} value={search} onFocus={() => setSearchOpen(true)} onChange={e => setSearch(e.target.value)} />{search && <Button variant="ghost" size="icon" className="size-7 shrink-0" aria-label="Clear search" onClick={() => { setSearch(''); setSearchOpen(false) }}><X className="size-3" /></Button>}</div><span className="hidden h-7 w-px bg-border sm:block" /><div className="flex size-8 items-center justify-center bg-brand-soft font-display text-xs font-bold text-primary sm:size-9">M</div></div></header>
      {section === 'Settings' ? <main className="mx-auto max-w-4xl px-5 py-10 sm:px-10"><p className="text-[11px] font-bold uppercase text-primary">Workspace settings / 03</p><h1 className="mt-3 font-display text-4xl font-bold">Settings<span className="text-primary">.</span></h1><div className="mt-10 grid gap-10 border-t border-border pt-8 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-muted-foreground">Profile</p><div className="mt-5 flex items-center gap-4"><div className="flex size-12 items-center justify-center bg-brand-soft font-display font-bold text-primary">M</div><div><p className="font-semibold">{profile.name}</p><p className="text-sm text-muted-foreground">{profile.role} · Buildicy</p></div></div></div><div><p className="text-xs font-bold uppercase text-muted-foreground">Calendar preferences</p><p className="mt-5 text-sm">Week starts on Monday</p><p className="mt-2 text-sm">Times shown in your local time zone</p><p className="mt-5 text-xs text-muted-foreground">Connected calendars and email reminders are coming in a future version.</p></div></div></main> : <main className="mx-auto max-w-[1700px]">
        <div className="border-b border-border px-5 pb-6 pt-7 sm:px-8 lg:px-10 lg:pt-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-[10px] font-bold uppercase text-primary">{section === 'Upcoming' ? 'Your agenda / 02' : 'Your workspace / 01'} <span className="ml-3 text-muted-foreground">— {format(today, 'EEEE, MMMM d')}</span></p><h1 className="font-display text-[34px] font-bold leading-none sm:text-[44px]">{section === 'Upcoming' ? 'Upcoming' : 'Your calendar'}<span className="text-primary">.</span></h1></div><Button onClick={() => create()} className="hidden h-10 rounded-sm px-5 font-semibold shadow-none sm:inline-flex"><Plus /> New meeting</Button></div></div>
        {section === 'Upcoming' ? <div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 lg:px-10"><div className="mb-5 flex items-baseline justify-between border-b border-border pb-4"><h2 className="font-display text-xl font-bold">On the horizon</h2><span className="text-xs font-semibold text-muted-foreground">{upcoming.length} meetings</span></div><UpcomingList meetings={upcoming} onOpen={open} long search={search} /></div> : <div className="grid xl:grid-cols-[minmax(0,1fr)_270px]"><div className="min-w-0 px-4 pb-12 pt-6 sm:px-8 lg:px-10"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-1 text-[10px] font-bold uppercase text-muted-foreground">{view} view <span className="mx-2">/</span> {format(cursor, 'yyyy')}</div><h2 className="font-display text-[28px] font-bold leading-tight capitalize sm:text-[34px]">{periodLabel}</h2></div><div className="flex items-center gap-2"><Button variant="outline" size="icon" className="size-9 rounded-sm shadow-none" aria-label="Previous period" onClick={() => move(-1)}><ChevronLeft /></Button><Button variant="outline" className="h-9 rounded-sm px-3 text-xs font-semibold shadow-none" onClick={() => { setCursor(today); setSelectedDate(today) }}>Today</Button><Button variant="outline" size="icon" className="size-9 rounded-sm shadow-none" aria-label="Next period" onClick={() => move(1)}><ChevronRight /></Button></div></div><div className="mb-5 flex w-max border border-border bg-card p-0.5">{views.map(option => <Button key={option} variant="ghost" onClick={() => setView(option)} className={`h-8 rounded-sm px-4 text-xs font-bold shadow-none ${view === option ? 'bg-foreground text-background hover:bg-foreground hover:text-background' : 'text-muted-foreground'}`}>{option}</Button>)}</div>
          {view === 'Month' ? <MonthView cursor={cursor} selected={selectedDate} meetings={filtered} onSelect={date => { setSelectedDate(date); create(date) }} onOpen={open} /> : <TimeView cursor={cursor} view={view} meetings={filtered} onSelect={date => { setSelectedDate(date); create(date) }} onOpen={open} />}
          <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2">{(['Client Meeting', 'Internal Meeting', 'Follow-up', 'Important', 'Other'] as MeetingType[]).map(type => <span key={type} className="flex items-center gap-1.5 text-[10px] text-muted-foreground"><span className={`size-1.5 ${eventColors[type]}`} />{type}</span>)}</div>
        </div><aside className="border-t border-border bg-panel px-6 py-7 xl:min-h-[calc(100vh-160px)] xl:border-l xl:border-t-0"><div className="flex items-baseline justify-between"><h3 className="font-display text-lg font-bold">Upcoming<span className="text-primary">.</span></h3><Button variant="link" className="h-auto p-0 text-[11px] font-bold" onClick={() => selectSection('Upcoming')}>View all <ChevronRight className="size-3" /></Button></div><div className="mt-2 text-xs text-muted-foreground">What’s next on your schedule</div><div className="mt-6"><UpcomingList meetings={upcoming.slice(0, 6)} onOpen={open} search={search} /></div><div className="mt-8 border-t border-border pt-6"><p className="text-[10px] font-bold uppercase text-muted-foreground">At a glance</p><div className="mt-4 grid grid-cols-3 gap-2 xl:grid-cols-1 xl:gap-0">{[['Today', todaysCount], ['This week', weekCount], ['Upcoming', upcoming.length]].map(([label, count]) => <div key={label} className="flex flex-col border-l-2 border-border pl-3 xl:flex-row xl:items-center xl:justify-between xl:border-l-0 xl:border-b xl:pl-0 xl:py-3"><span className="text-[10px] font-semibold uppercase text-muted-foreground">{label}</span><span className="font-display text-xl font-bold xl:text-base">{count}</span></div>)}</div></div></aside></div>}
      </main>}
    </div>
    {section !== 'Settings' && <Button aria-label="Create meeting" onClick={() => create()} className="fixed bottom-5 right-5 z-20 size-14 rounded-full shadow-lg sm:hidden"><Plus className="size-6" /></Button>}
    <MeetingDialog meeting={active} mode={dialogMode} onClose={() => setActive(null)} onSave={save} onDelete={remove} onDuplicate={duplicate} onEdit={() => setDialogMode('edit')} />
  </div>
}

function EventCard({ meeting, onOpen, compact = false }: { meeting: Meeting; onOpen: (meeting: Meeting) => void; compact?: boolean }) {
  return <Button variant="ghost" onClick={e => { e.stopPropagation(); onOpen(meeting) }} title={`${formatTime(meeting.startTime)} · ${meeting.title}`} className={`flex h-auto min-w-0 w-full items-center justify-start gap-1.5 overflow-hidden rounded-[2px] border-l-[3px] ${eventBorders[meeting.color]} bg-secondary/70 px-1.5 py-1 text-left text-[10px] font-medium text-foreground shadow-none hover:bg-accent sm:px-2 ${compact ? 'py-1' : 'py-1.5'}`}><span className="shrink-0 font-bold">{meeting.startTime}</span><span className="truncate">{meeting.title}</span></Button>
}
function MonthView({ cursor, selected, meetings, onSelect, onOpen }: { cursor: Date; selected: Date; meetings: Meeting[]; onSelect: (date: Date) => void; onOpen: (meeting: Meeting) => void }) {
  const days = eachDayOfInterval({ start: startOfWeek(startOfMonth(cursor), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(cursor), { weekStartsOn: 1 }) })
  const grouped = useMemo(() => Object.groupBy(meetings, m => m.date), [meetings])
  return <div className="overflow-hidden border border-border bg-card"><div className="grid calendar-grid border-b border-border bg-panel">{['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'].map(day => <div key={day} className="px-1 py-3 text-center text-[9px] font-bold text-muted-foreground sm:text-[10px]">{day}</div>)}</div><div className="grid calendar-grid">{days.map(day => { const key = format(day, 'yyyy-MM-dd'); const items = grouped[key] || []; const current = isSameDay(day, today); const selectedDay = isSameDay(day, selected); return <div key={key} role="button" tabIndex={0} aria-label={`Create meeting on ${format(day, 'MMMM d, yyyy')}`} onClick={() => onSelect(day)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(day) } }} className={`group relative min-w-0 min-h-[76px] cursor-pointer border-b border-r border-border p-1 transition-colors hover:bg-brand-soft/50 focus-visible:outline-2 focus-visible:outline-primary sm:min-h-[112px] sm:p-2 lg:min-h-[126px] ${!isSameMonth(day, cursor) ? 'bg-muted/40 text-muted-foreground' : ''} ${selectedDay && !current ? 'bg-brand-soft/50' : ''}`}><div className="mb-1 flex items-center justify-between"><span className={`flex size-6 items-center justify-center font-display text-xs font-bold sm:size-7 sm:text-sm ${current ? 'bg-primary text-primary-foreground' : ''}`}>{format(day, 'd')}</span><Plus className="hidden size-3.5 text-primary group-hover:block" /></div><div className="space-y-1">{items.slice(0, 2).map(m => <EventCard key={m.id} meeting={m} onOpen={onOpen} compact />)}{items.length > 2 && <span className="block pl-1 text-[9px] font-bold text-primary">+{items.length - 2} more</span>}</div></div> })}</div></div>
}
function TimeView({ cursor, view, meetings, onSelect, onOpen }: { cursor: Date; view: View; meetings: Meeting[]; onSelect: (date: Date) => void; onOpen: (meeting: Meeting) => void }) {
  const days = view === 'Day' ? [cursor] : Array.from({ length: 7 }, (_, i) => addDays(startOfWeek(cursor, { weekStartsOn: 1 }), i))
  return <div className="overflow-hidden border border-border bg-card"><div className={`grid border-b border-border bg-panel ${view === 'Week' ? 'calendar-grid' : ''}`}>{days.map(day => <div key={day.toISOString()} className="border-r border-border p-3 text-center"><div className="text-[10px] font-bold text-muted-foreground">{format(day, 'EEE').toUpperCase()}</div><div className={`mx-auto mt-1 flex size-7 items-center justify-center font-display text-sm font-bold ${isSameDay(day, today) ? 'bg-primary text-primary-foreground' : ''}`}>{format(day, 'd')}</div></div>)}</div><div className={`grid ${view === 'Week' ? 'calendar-grid' : ''}`}>{days.map(day => { const items = meetings.filter(m => m.date === format(day, 'yyyy-MM-dd')); return <div key={day.toISOString()} className="min-h-[350px] min-w-0 space-y-2 border-r border-border p-2 sm:p-3">{items.map(m => <div key={m.id} className="min-w-0"><EventCard meeting={m} onOpen={onOpen} /><div className="hidden pl-2 pt-1 text-[10px] text-muted-foreground sm:block">{formatTime(m.startTime)} – {formatTime(m.endTime)}</div></div>)}<Button variant="ghost" onClick={() => onSelect(day)} className="h-8 w-full justify-start rounded-sm px-1 text-[10px] text-muted-foreground opacity-70 hover:text-primary sm:px-2"><Plus className="size-3" /><span className="hidden sm:inline">Add meeting</span></Button></div> })}</div></div>
}
function UpcomingList({ meetings, onOpen, long = false, search }: { meetings: Meeting[]; onOpen: (meeting: Meeting) => void; long?: boolean; search: string }) {
  if (!meetings.length) return <div className="py-10 text-center"><CalendarDays className="mx-auto size-7 text-primary/50" /><p className="mt-3 text-sm font-semibold">{search ? 'No matching meetings' : 'Nothing on the horizon'}</p><p className="mt-1 text-xs text-muted-foreground">{search ? 'Try another search.' : 'Your upcoming meetings will appear here.'}</p></div>
  let previous = ''
  return <div className="space-y-1">{meetings.map(m => { const date = parseISO(m.date); const group = isSameDay(date, today) ? 'TODAY' : isSameDay(date, addDays(today, 1)) ? 'TOMORROW' : format(date, 'MMM d').toUpperCase(); const showGroup = previous !== group; previous = group; return <div key={m.id}>{showGroup && <p className={`text-[10px] font-bold text-muted-foreground ${long ? 'mt-8 mb-3' : 'mt-5 mb-3'}`}>{group}</p>}<Button variant="ghost" onClick={() => onOpen(m)} className={`group flex h-auto w-full items-start gap-3 rounded-sm border border-transparent bg-card p-3 text-left shadow-none hover:border-border hover:bg-card ${long ? 'sm:p-5' : ''}`}><span className={`mt-1.5 size-2 shrink-0 ${eventColors[m.color]}`} /><span className="min-w-0 flex-1"><span className={`block truncate font-semibold ${long ? 'text-sm sm:text-base' : 'text-xs'}`}>{m.title}</span><span className="mt-1 block truncate text-[11px] font-normal text-muted-foreground">{m.client || m.type}</span></span><span className="shrink-0 text-[10px] font-bold text-muted-foreground">{formatTime(m.startTime)}</span></Button></div> })}</div>
}
